"""Alpha-Scalp Bot – HypothesisTracker (GP Step 10 / Part B).

Manages the full lifecycle of loss-pattern hypotheses generated by
DeepSeekPitBoss. Each hypothesis is shadow-tested against live trade
outcomes before any block condition is approved.

Lifecycle:
  SHADOW_TESTING → (150 trades) → 5 statistical tests → APPROVED / REJECTED
  APPROVED       → (100 live trades) → sunset check → SUNSETTED (if degraded)

5 Auto-Approval Tests (no human expertise needed):
  1. Sample size  >= 150 shadow trades
  2. Loss block rate >= 0.65
  3. Win block rate  <= 0.20
  4. Regimes validated >= 2
  5. Edge ratio (loss_block / win_block) >= 2.5

Hybrid LLM:
  Edge ratio 2.3–3.5 (borderline) → DeepSeek context check
  Edge ratio < 2.3               → AUTO_REJECT
  Edge ratio > 3.5               → AUTO_APPROVE (no LLM needed)
  LLM returns UNCERTAIN          → extend shadow +50 trades

Meta-Validator:
  Weekly: if approved hypotheses collectively < 55% accurate → suspend all
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Awaitable

from loguru import logger


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HYPOTHESES_FILE = Path("shadow_hypotheses.jsonl")
_REGISTRY_FILE   = Path("block_conditions_registry.json")

MIN_SHADOW_TRADES:      int   = 150
MIN_LOSS_BLOCK_RATE:    float = 0.65
MAX_WIN_BLOCK_RATE:     float = 0.20
MIN_EDGE_RATIO:         float = 2.5
MIN_REGIMES:            int   = 2
SOFT_BLOCK_THRESHOLD:   float = 3.5   # edge >= 3.5 → HARD_BLOCK, else SOFT_BLOCK
BORDERLINE_LOW:         float = 2.3   # below → auto-reject without LLM
BORDERLINE_HIGH:        float = 3.5   # above → auto-approve without LLM
SUNSET_INTERVAL_TRADES: int   = 100
SUNSET_DEGRADATION_PCT: float = 0.30
META_MIN_ACCURACY:      float = 0.55
MAX_ACTIVE_CONDITIONS:  int   = 5
SHADOW_EXTEND_TRADES:   int   = 50    # LLM returns UNCERTAIN → extend by this
OVERLAP_THRESHOLD:      float = 0.70  # FIX-7: Jaccard similarity above this → reject duplicate


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Hypothesis:
    """One loss-pattern hypothesis in shadow testing."""
    hypothesis_id:          str
    pattern_key:            str
    rule_description:       str
    status:                 str    = "SHADOW_TESTING"   # SHADOW_TESTING|APPROVED|REJECTED|SUNSETTED
    target_shadow_trades:   int    = MIN_SHADOW_TRADES
    shadow_trades_completed:int    = 0
    losses_blocked:         int    = 0
    wins_blocked:           int    = 0
    total_losses_seen:      int    = 0
    total_wins_seen:        int    = 0
    regimes_effective:      list   = field(default_factory=list)
    edge_ratio:             float  = 0.0
    confidence_tier:        str    = "HARD_BLOCK"
    approved_at:            str | None = None
    live_trades_since_approval: int = 0
    approval_loss_block_rate: float = 0.0
    created_at:             str    = field(default_factory=lambda: _now_iso())
    source_finding_id:      str    = ""

    # ── computed rates ──────────────────────────────────────────────────

    @property
    def loss_block_rate(self) -> float:
        return self.losses_blocked / self.total_losses_seen if self.total_losses_seen else 0.0

    @property
    def win_block_rate(self) -> float:
        return self.wins_blocked / self.total_wins_seen if self.total_wins_seen else 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "hypothesis_id":           self.hypothesis_id,
            "pattern_key":             self.pattern_key,
            "rule_description":        self.rule_description,
            "status":                  self.status,
            "target_shadow_trades":    self.target_shadow_trades,
            "shadow_trades_completed": self.shadow_trades_completed,
            "losses_blocked":          self.losses_blocked,
            "wins_blocked":            self.wins_blocked,
            "total_losses_seen":       self.total_losses_seen,
            "total_wins_seen":         self.total_wins_seen,
            "regimes_effective":       self.regimes_effective,
            "edge_ratio":              self.edge_ratio,
            "confidence_tier":         self.confidence_tier,
            "approved_at":             self.approved_at,
            "live_trades_since_approval": self.live_trades_since_approval,
            "approval_loss_block_rate":self.approval_loss_block_rate,
            "created_at":              self.created_at,
            "source_finding_id":       self.source_finding_id,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Hypothesis":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# HypothesisTracker
# ---------------------------------------------------------------------------

class HypothesisTracker:
    """Manages shadow testing and auto-approval of loss-pattern hypotheses.

    Parameters
    ----------
    llm_caller : async callable, optional
        Signature: async (hypothesis_text: str, stats: dict) -> str
        Returns "GENUINE", "NOISE", or "UNCERTAIN".
        Injected for testability. If None, borderline cases auto-reject.
    hypotheses_path : Path, optional
        Override for shadow_hypotheses.jsonl location.
    registry_path : Path, optional
        Override for block_conditions_registry.json location.
    telegram : TelegramAlerts-like, optional
        If provided, sends Telegram alerts on approve/reject/sunset.
    """

    def __init__(
        self,
        llm_caller: Callable | None = None,
        hypotheses_path: Path | str | None = None,
        registry_path:   Path | str | None = None,
        telegram: Any | None = None,
    ) -> None:
        self._hyp_path  = Path(hypotheses_path or _HYPOTHESES_FILE)
        self._reg_path  = Path(registry_path   or _REGISTRY_FILE)
        self._llm       = llm_caller
        self._telegram  = telegram
        self._active: dict[str, Hypothesis] = {}   # id → Hypothesis
        self._system_suspended: bool = False
        self._load_hypotheses()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_hypothesis(self, pattern_key: str, rule_description: str,
                       finding_id: str = "") -> "Hypothesis | None":
        """Create a new hypothesis and begin shadow testing.

        Returns None (FIX-7) if a semantically overlapping hypothesis already
        exists among active/shadow-testing entries (Jaccard > OVERLAP_THRESHOLD).
        """
        for existing in self._active.values():
            if existing.status in ("REJECTED", "SUNSETTED"):
                continue
            sim = _jaccard_similarity(rule_description, existing.rule_description)
            if sim > OVERLAP_THRESHOLD:
                logger.info(
                    "HypothesisTracker: overlap {:.0%} — rejected '{}' (matches {} '{}')",
                    sim, pattern_key, existing.hypothesis_id, existing.pattern_key,
                )
                return None

        h_id = f"H{str(uuid.uuid4())[:6].upper()}"
        h = Hypothesis(
            hypothesis_id=h_id,
            pattern_key=pattern_key,
            rule_description=rule_description,
            source_finding_id=finding_id,
        )
        self._active[h_id] = h
        self._append_hypothesis(h)
        logger.info("HypothesisTracker: new hypothesis {} — {}", h_id, pattern_key)
        return h

    def on_trade_close(
        self,
        pattern_keys: set[str],
        regime: str,
        is_win: bool,
    ) -> None:
        """Record a closed trade outcome against all SHADOW_TESTING hypotheses.

        Parameters
        ----------
        pattern_keys : set[str]
            Patterns present at trade entry.
        regime : str
            Regime at trade entry.
        is_win : bool
            Whether the trade was profitable.
        """
        for h in list(self._active.values()):
            if h.status != "SHADOW_TESTING":
                continue

            would_block = h.pattern_key in pattern_keys

            if is_win:
                h.total_wins_seen += 1
                if would_block:
                    h.wins_blocked += 1
            else:
                h.total_losses_seen += 1
                if would_block:
                    h.losses_blocked += 1
                    if regime not in h.regimes_effective:
                        h.regimes_effective.append(regime)

            h.shadow_trades_completed += 1

            if h.shadow_trades_completed >= h.target_shadow_trades:
                self._evaluate_sync(h)

        self._save_all()

    def on_live_trade_close(self, pattern_keys: set[str], is_win: bool) -> None:
        """Track approved hypothesis performance post-approval (sunset check).

        Called for every LIVE trade close (not shadow).
        """
        for h in list(self._active.values()):
            if h.status != "APPROVED":
                continue

            h.live_trades_since_approval += 1

            if h.live_trades_since_approval % SUNSET_INTERVAL_TRADES == 0:
                self._check_sunset(h, pattern_keys, is_win)

        self._save_all()

    def meta_validate(self, recent_trades: list[dict[str, Any]]) -> bool:
        """Weekly check: is the hypothesis system helping or hurting?

        Returns True if system is healthy, False if suspended.
        """
        approved = [h for h in self._active.values() if h.status == "APPROVED"]
        if not approved:
            return True

        # For each approved hypothesis, check trades it blocked
        # Were those actual losses? (good) or wins? (bad)
        blocked_trades  = [t for t in recent_trades if t.get("blocked_by")]
        if len(blocked_trades) < 10:
            return True   # not enough data yet

        correct_blocks = sum(1 for t in blocked_trades if not t.get("is_win", True))
        accuracy = correct_blocks / len(blocked_trades)

        if accuracy < META_MIN_ACCURACY:
            self._system_suspended = True
            logger.warning(
                "HypothesisTracker: meta-validator SUSPENDED system — accuracy={:.0%} < {:.0%}",
                accuracy, META_MIN_ACCURACY,
            )
            self._send_telegram(
                f"⚠️ Learning system suspended — block accuracy {accuracy:.0%} below threshold"
            )
            return False

        if self._system_suspended:
            self._system_suspended = False
            logger.info("HypothesisTracker: meta-validator RESUMED system — accuracy={:.0%}", accuracy)
            self._send_telegram(f"🧠 Learning system resumed — accuracy {accuracy:.0%}")

        return True

    @property
    def system_suspended(self) -> bool:
        return self._system_suspended

    def get_active_hypotheses(self) -> list[Hypothesis]:
        return list(self._active.values())

    def get_approved(self) -> list[Hypothesis]:
        return [h for h in self._active.values() if h.status == "APPROVED"]

    # ------------------------------------------------------------------
    # Evaluation (sync wrapper — async LLM handled separately)
    # ------------------------------------------------------------------

    def _evaluate_sync(self, h: Hypothesis) -> None:
        """Run 5 statistical tests. Handles non-borderline cases without LLM."""
        # Test 1 — sample size
        total = h.total_losses_seen + h.total_wins_seen
        if total < MIN_SHADOW_TRADES:
            self._reject(h, "insufficient_sample")
            return

        # Test 2 — loss block rate
        lbr = h.loss_block_rate
        if lbr < MIN_LOSS_BLOCK_RATE:
            self._reject(h, f"weak_loss_filter (lbr={lbr:.2f})")
            return

        # Test 3 — win preservation
        wbr = h.win_block_rate
        if wbr > MAX_WIN_BLOCK_RATE:
            self._reject(h, f"blocks_too_many_wins (wbr={wbr:.2f})")
            return

        # Test 4 — regime consistency
        if len(h.regimes_effective) < MIN_REGIMES:
            self._reject(h, f"single_regime_overfit ({h.regimes_effective})")
            return

        # Test 5 — edge ratio
        edge = lbr / wbr if wbr > 0 else lbr / 0.01  # avoid div-by-zero
        h.edge_ratio = round(edge, 3)

        if edge < BORDERLINE_LOW:
            self._reject(h, f"insufficient_edge_ratio ({edge:.2f})")
            return

        if edge >= BORDERLINE_HIGH:
            # Clear approve — no LLM needed
            self._approve(h)
            return

        # Borderline zone (2.3–3.5) — try LLM if available, else auto-reject
        if self._llm is None:
            self._reject(h, f"borderline_no_llm (edge={edge:.2f})")
            return

        # Flag for async LLM evaluation — caller must call evaluate_borderline_async()
        h.status = "PENDING_LLM"
        logger.info("HypothesisTracker: {} PENDING_LLM — edge={:.2f}", h.hypothesis_id, edge)

    async def evaluate_borderline_async(self, h: Hypothesis) -> None:
        """Call DeepSeek for borderline hypotheses. Awaited by PitBoss."""
        if self._llm is None or h.status != "PENDING_LLM":
            return
        try:
            result = await self._llm(
                hypothesis=h.rule_description,
                stats={
                    "loss_block_rate": h.loss_block_rate,
                    "win_block_rate":  h.win_block_rate,
                    "edge_ratio":      h.edge_ratio,
                    "regimes":         h.regimes_effective,
                    "shadow_trades":   h.shadow_trades_completed,
                },
            )
            result = result.strip().upper()
            if result == "GENUINE":
                self._approve(h)
            elif result == "NOISE":
                self._reject(h, "llm_noise_verdict")
            else:  # UNCERTAIN
                h.target_shadow_trades += SHADOW_EXTEND_TRADES
                h.status = "SHADOW_TESTING"
                logger.info(
                    "HypothesisTracker: {} UNCERTAIN — extending shadow +{} trades",
                    h.hypothesis_id, SHADOW_EXTEND_TRADES,
                )
        except Exception as exc:
            logger.error("HypothesisTracker: LLM call failed for {} — {}", h.hypothesis_id, exc)
            self._reject(h, "llm_error")

        self._save_all()

    # ------------------------------------------------------------------
    # Approve / Reject / Sunset
    # ------------------------------------------------------------------

    def _approve(self, h: Hypothesis) -> None:
        active_approved = len(self.get_approved())
        if active_approved >= MAX_ACTIVE_CONDITIONS:
            self._reject(h, f"max_active_conditions_reached ({MAX_ACTIVE_CONDITIONS})")
            return

        h.status = "APPROVED"
        h.approved_at = _now_iso()
        h.approval_loss_block_rate = h.loss_block_rate
        h.confidence_tier = "HARD_BLOCK" if h.edge_ratio >= SOFT_BLOCK_THRESHOLD else "SOFT_BLOCK"

        logger.info(
            "HypothesisTracker: APPROVED {} | edge={:.2f} tier={} pattern={}",
            h.hypothesis_id, h.edge_ratio, h.confidence_tier, h.pattern_key,
        )
        self._write_registry()
        self._send_telegram(
            f"🧠 {h.hypothesis_id} auto-approved | Edge {h.edge_ratio:.1f} | "
            f"{h.confidence_tier} active now"
        )

    def _reject(self, h: Hypothesis, reason: str) -> None:
        h.status = "REJECTED"
        logger.info("HypothesisTracker: REJECTED {} — {}", h.hypothesis_id, reason)
        self._send_telegram(f"🚫 {h.hypothesis_id} rejected — {reason}")

    def _check_sunset(self, h: Hypothesis, pattern_keys: set[str], is_win: bool) -> None:
        """Sunset if recent live performance degraded > 30% vs approval stats."""
        if h.live_trades_since_approval < SUNSET_INTERVAL_TRADES:
            return

        # Approximate recent block accuracy from approval stats
        original = h.approval_loss_block_rate
        if original == 0:
            return

        # Current loss_block_rate from shadow (proxy for live performance)
        current = h.loss_block_rate
        degradation = (original - current) / original if original > 0 else 0.0

        if degradation > SUNSET_DEGRADATION_PCT:
            h.status = "SUNSETTED"
            logger.info(
                "HypothesisTracker: SUNSETTED {} — degradation={:.0%}",
                h.hypothesis_id, degradation,
            )
            self._write_registry()
            self._send_telegram(
                f"📉 {h.hypothesis_id} auto-sunsetted — effectiveness dropped {degradation:.0%}"
            )

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load_hypotheses(self) -> None:
        """Load all hypotheses from JSONL file."""
        if not self._hyp_path.exists():
            return
        try:
            for line in self._hyp_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line:
                    continue
                d = json.loads(line)
                h = Hypothesis.from_dict(d)
                if h.status in ("SHADOW_TESTING", "APPROVED", "PENDING_LLM"):
                    self._active[h.hypothesis_id] = h
            logger.info("HypothesisTracker loaded {} active hypotheses", len(self._active))
        except Exception as exc:
            logger.error("HypothesisTracker load failed: {}", exc)

    def _append_hypothesis(self, h: Hypothesis) -> None:
        """Append a new hypothesis to JSONL."""
        try:
            with open(self._hyp_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(h.to_dict()) + "\n")
        except Exception as exc:
            logger.error("HypothesisTracker append failed: {}", exc)

    def _save_all(self) -> None:
        """Rewrite entire JSONL with current state (all hypotheses)."""
        try:
            lines = [json.dumps(h.to_dict()) for h in self._active.values()]
            self._hyp_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        except Exception as exc:
            logger.error("HypothesisTracker save failed: {}", exc)

    def _write_registry(self) -> None:
        """Write block_conditions_registry.json with currently approved hypotheses."""
        approved = [
            {
                "hypothesis_id":   h.hypothesis_id,
                "pattern_key":     h.pattern_key,
                "confidence_tier": h.confidence_tier,
                "edge_ratio":      h.edge_ratio,
                "approved_at":     h.approved_at,
                "live_trades_since_approval": h.live_trades_since_approval,
                "active":          h.status == "APPROVED",
            }
            for h in self._active.values()
            if h.status in ("APPROVED", "SUNSETTED")
        ]
        try:
            self._reg_path.write_text(
                json.dumps(approved, indent=2), encoding="utf-8"
            )
            logger.info("BlockConditions registry written: {} entries", len(approved))
        except Exception as exc:
            logger.error("HypothesisTracker registry write failed: {}", exc)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _send_telegram(self, message: str) -> None:
        if self._telegram and getattr(self._telegram, "enabled", False):
            import asyncio
            try:
                asyncio.get_event_loop().create_task(
                    self._telegram.send_message(message)
                )
            except Exception:
                pass


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _jaccard_similarity(a: str, b: str) -> float:
    """Token-level Jaccard similarity between two strings. No external deps.

    Splits on non-alphanumeric chars, lowercases, then computes
    |A ∩ B| / |A ∪ B|. Returns 1.0 if both strings are empty.
    """
    tokens_a = set(re.findall(r"[a-z0-9]+", a.lower()))
    tokens_b = set(re.findall(r"[a-z0-9]+", b.lower()))
    if not tokens_a and not tokens_b:
        return 1.0
    if not tokens_a or not tokens_b:
        return 0.0
    return len(tokens_a & tokens_b) / len(tokens_a | tokens_b)
